---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
        namespace: flux-system
      version: 3.2.3
  releaseName: oauth2-proxy
  targetNamespace: identity
  interval: 5m
  values:
    # image:
    #   repository: quay.io/pusher/oauth2_proxy
    #   tag: v6.1.1
    # replicaCount: 1
    ingress:
      enabled: false
