---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: litmus-chaos
  namespace: flux-system
spec:
  interval: 10m0s
  # For ServiceMonitor CRD
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/prod/litmus/litmus-chaos
  prune: true
  validation: client