---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 10m0s
  # For ServiceMonitor CRD
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/prod/identity/oauth2-proxy
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: oauth2-proxy
      namespace: flux-system