---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: osm
  namespace: osm-system
spec:
  values:
    OpenServiceMesh:
      enablePrometheus: false
      enableGrafana: false
      enableFluentbit: false
      deployJaeger: false
