# labels to be used with /area command
area:
  - 'gcp'
  - 'aws'
  - 'azure'
  - 'kubernetes'


# File globs for PR labeler
# tests:
#   - '**/*.test.ts'

'area/kubernetes':
  - kubernetes/*
  - kubernetes/**/*

'area/gcp':
  - iac/gcp/*
  - iac/gcp/**/*

'area/aws':
  - iac/aws/*
  - iac/aws/**/*

'area/azure':
  - iac/azure/*
  - iac/azure/**/*

'kind/documentation':
  - docs/*
  - docs/**/*