apiVersion: v1
data:
    object-store.yaml: ENC[AES256_GCM,data:qkvtWhG9Eo3dAkVNUblf8LxBtgQIaIp7pu+UNlduCeCzwlqhveIsF5x8DyKwvwWEQs0ODXlqkZ15C9Lx52ICerU6/Gs=,iv:QuKLy2YWiw+FfR/gAJ5ubIzFGHw/TpM/o0I2d1CUXSI=,tag:Y5ig2vDieoQNRcMAVrgQXA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: thanos-object-storage
    namespace: monitoring
sops:
    kms: []
    gcp_kms:
    -   resource_id: projects/portefaix-prod/locations/europe-west1/keyRings/portefaix-prod-sops/cryptoKeys/portefaix-prod-sops
        created_at: '2020-11-29T08:50:00Z'
        enc: CiQAq0sbAzL2FMvRoPIMx9bAy6BcKhFoXmcf8Lt5+8Hqq4RCwVYSSQB2jcG5HiRDwaOc7CoAYRY3umpCZbCN7msyHLSuyyw9WjYrdBRmYPtARgNPUnJW+TfLjJgdAudVCmGj6LqrbNaZskLMMhHGR1E=
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-29T08:50:00Z'
    mac: ENC[AES256_GCM,data:XjlDeQNUsl4ha8tps59/uyrHJ3+/eJKdEkyDoceZP9Z4T0K6tvVIwibnu4O2YQFyZf1iCiuqFey1d5NzBdpBa1/RIeCBYcpYKAIjH/0Vze33z8fXsfoGq+YbB0doi7uxvmaSFxmLNk5eLwnn0cfH3lhHhHUi16Zn6ej4Ci6jokU=,iv:KvN9D+X6PO/dFavb66dktzvVhwQRmkxoRHHHl22xy6c=,tag:9qh3fzZY23cZrf70TXzNUA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)
    version: 3.6.1
