# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  {{- if .Values.additionalAnnotations }}
  annotations:
  {{ toYaml .Values.additionalAnnotations | indent 4 }}
  {{- end }}
  labels:
    {{- include "opentelemetry-collector.labels" . | indent 4 }}
    portefaix.xyz/version: v0.43.0
  name: {{ .Values.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  image: {{ .Values.collector.image.repository }}:{{ .Values.collector.image.tag }}
  mode: {{ .Values.mode }}
  serviceAccount: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  {{- with .Values.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.extraEnvs }}
  env:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.envFrom }}
  envFrom:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if eq .Values.mode "statefulset" }}
  targetAllocator:
    enabled: true
    image: {{ .Values.targetAllocator.image.repository }}:{{ .Values.targetAllocator.image.tag }}
    replicas: {{ .Values.targetAllocator.replicas }}
    serviceAccount: {{ .Values.name }}-targetallocator
    prometheusCR:
      enabled: {{ .Values.targetAllocator.prometheusCR.enabled }}
{{- end }}
  config: |
    {{- toYaml .Values.config | nindent 4 }}
