# Copyright (C) 2020 Nicolas Lamirault <nicolas.lamirault@gmail.com>

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

site_name: Kubernetes Portefaix Lab
site_author: Nicolas Lamirault
site_url: https://www.portefaix.xyz
site_description: >-
  Gitops with Kubernetes

copyright: Copyright &copy; 2020 Nicolas Lamirault

repo_name: nlamirault/portefaix-lab
repo_url: https://github.com/nlamirault/portefaix-lab
edit_uri: ""

# theme:
#   name: material
#   logo: _files/flux-icon@2x.png
#   language: en
#   palette:
#     primary: indigo
#   custom_dir: mkdocs/
#   features:
#     - navigation.tabs

# Configuration
theme:
  name: material
  custom_dir: mkdocs

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    #- navigation.instant
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

docs_dir: docs

extra_css:
  - _static/custom.css

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nlamirault
    - icon: fontawesome/brands/github
      link: https://github.com/nlamirault/portefaix-lab

plugins:
  - search
  # - mkpdfs:
  #     company: Skale-5
  #     author: Ops Team

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # - pymdownx.superfences:
  #     highlight_code: true
  # - pymdownx.tabbed
  # - pymdownx.tilde
  # - pymdownx.progressbar
  # - pymdownx.tasklist
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Introduction: index.md
  - Infrastructure:
      - Local: infrastructure/local.md
      - GKE: infrastructure/gke.md
  - Users:
      - Gitops: user/flux.md
      - Stacks:
        - Certificates:
          - Description: stacks/cert-manager/index.md
          - Cert Manager: stacks/cert-manager/cert-manager.md
          - Letsencrypt: stacks/cert-manager/letsencrypt.md
        - DNS: stacks/dns/index.md
        - Identity: stacks/identity/index.md
        - Ingress Controllers:
          - Description: stacks/ingress-controllers/index.md
          - Default Backend: stacks/ingress-controllers/default-backend.md
          - Nginx Ingress Controllers: stacks/ingress-controllers/ingress-nginx.md
        - Logging:
          - Description: stacks/logging/index.md
          - Filebeat: stacks/logging/filebeat.md
          - Loki: stacks/logging/loki.md
          - Promtail: stacks/logging/promtail.md
        - Monitoring:
          - Description: stacks/monitoring/index.md
          - Alertmanager: stacks/monitoring/alertmanager.md
          - Blackbox Exporter: stacks/monitoring/blackbox-exporter.md
          - Grafana: stacks/monitoring/grafana.md
          - Kube Monitors AKS: stacks/monitoring/kube-monitors-aks.md
          - Kube Monitors EKS: stacks/monitoring/kube-monitors-eks.md
          - Kube Monitors GKE: stacks/monitoring/kube-monitors-gke.md
          - Kube Monitors K3S: stacks/monitoring/kube-monitors-k3s.md
          - Kube State Metrics: stacks/monitoring/kube-state-metrics.md
          - Node Exporter: stacks/monitoring/node-exporter.md
          - Prometheus: stacks/monitoring/prometheus.md
          - Prometheus Operator: stacks/monitoring/prometheus-operator.md
          - Pushgateway: stacks/monitoring/pushgateway.md
          - Thanos: stacks/monitoring/thanos.md
        - Reporting:
          - Description: stacks/reporting/index.md
          - Kube Resource Report: stacks/reporting/kube-resource-report.md
          - Polaris: stacks/reporting/polaris.md
        - Security:
          - Description: stacks/security/index.md
          - OpenPolicyAgent: stacks/security/open-policy-agent.md
  - Troubleshooting: troubleshooting.md
  - Roadmap: roadmap.md
  - Reference: reference/reference.md
  - Glossary: reference/glossary.md
  - Contributing: CONTRIBUTING.md
