# Default values for thanos-mixin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Provide a name to substitute for the full names of resources
##
fullnameOverride: ""
