---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: notification-controller
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: notification-controller
  podMetricsEndpoints:
    - port: http-prom