apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: thanos-objstore-config
  namespace: monitoring
spec:
  encryptedData:
    object-store.yaml: AgCChfpjgbinRHEHQU7FsRtUsOpGJO1i5lDYBq2235x8awfbmYS6m3AXoCpuVe2gl9yw8SseK6+gFzk6gv6tVLn77W8DZFy7MjziGmL435/ZJVb62QQTN5bW+u3xtnhFM0axGHvGvO0ymWaX+TB72VEPWPM01moaWFt+12qs5FVVwRm6VmsqXAYRB/7zq7+pMmZOIDNE1KiLA6Iq5nsCF+xZVI6E5Wls7lVhXIJC6ktwJJPw8ome3QfSe75fQYRcOEWoXPmGitTScWjWQx+7c4+Q2M7y9cqMLaxalHO3pwhBXh4zHOhBAFIkUfPsi+aJCfO+ARSVN88cDIkAEkUcPUvl7SCVdL2TxaV8ZPTLg1OcEdUVP47dSo6iXBkOPdfaSnZJVnP3cGkFixYdnRb9gmLi75+oMoEFbDycr88naNIJ+tNcscS2iI0g2K1dj7DtHlUYeLFsCan5KEOjMVKv7qUNgsGNE0PRjM4/wM1OHcfQ79Cx7MvIeM0YzMN2ZRKzfenjYAtGpmbuj/J8reClBCW90jdsyfEmFd/Qf015rKwy3mmAjPAAzb4cjxy4mDRCtNq+Mu7B0nezTLly5HZ6EW4KH/TxPNQaTX9HQRZh/7DBlfdr0EXx7/9W+EJUG9Rio7IK5UzyUt8m1ixZ6eO5E/yIQJ61GWA6kL/0IM5DtVJvjtg7riJiCeWYjJWqbHdCrbX0Hq+n5VDxEaKL0Fxrz/rcM/zluZ5EMU7H0wUzlidHJhffvBt3+kNd7C0AiiMZ6a3E2pVPXVg=
  template:
    metadata:
      creationTimestamp: null
      name: thanos-objstore-config
      namespace: monitoring

