---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 0.3.29
      sourceRef:
        kind: HelmRepository
        name: banzaicloud-charts
        namespace: flux-system
      interval: 5m
  releaseName: thanos
  targetNamespace: monitoring
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # Depends on having sealed-secret to un-encrypted required secrets: thanos-objstore-config.
  dependsOn:
    - name: sealed-secrets
      namespace: flux-system
  values:
    image:
      repository: quay.io/thanos/thanos
      tag: v0.15.0
    objstoreSecretOverride: thanos-objstore-config
    query:
      enabled: true
      serviceAccount: thanos-k8s
      # replicaCount: 1
      # replicaLabels:
      #   - replica
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 300m
          memory: 1Gi
      http:
        ingress:
          enabled: false
          # annotations:
          #   kubernetes.io/ingress.class: nginx
          #   cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          #   nginx.ingress.kubernetes.io/auth-url: 'https://portefaix.xyz/oauth2/auth'
          #   nginx.ingress.kubernetes.io/auth-signin: 'https://portefaix.xyz/oauth2/start?rd=$escaped_request_uri'
          # hosts:
          #   - thanos.portefaix.xyz
          # tls:
          #   - secretName: thanos.portefaix.xyz-tls
          #     hosts:
          #       - thanos.portefaix.xyz
      metrics:
        serviceMonitor:
          enabled: true
    store:
      enabled: true
      serviceAccount: thanos-k8s
      metrics:
        serviceMonitor:
          enabled: true
    compact:
      enabled: true
      serviceAccount: thanos-k8s
      metrics:
        serviceMonitor:
          enabled: true
    bucket:
      enabled: true
      serviceAccount: thanos-k8s
      metrics:
        serviceMonitor:
          enabled: true
    rule:
      enabled: false
    sidecar:
      enable: true
      serviceAccount: thanos-k8s
      metrics:
        serviceMonitor:
          enabled: true
  # valuesFrom:
  #   - kind: Secret
  #     name: thanos-objstore-config