---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: kubernetes-ingress-nginx
        namespace: flux-system
      version: 3.7.1
  interval: 10m0s
  releaseName: ingress-nginx
  targetNamespace: ingress-controllers
  values:
    controller:
      config:
        use-proxy-protocol: "true"
      # service:
      #   type: NodePort
      #   nodePorts:
      #     http: 30080
      #     https: 30443
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
        limits:
          cpu: 2
          memory: 500Mi
    defaultBackend:
      resources:
        requests:
          cpu: 10m
          memory: 20Mi
        limits:
          cpu: 10m
          memory: 20Mi
