---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
patchesJson6902:
- target:
    version: v1
    kind: ServiceAccount
    name: default
  path: ./patch-serviceAccount.yaml