---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m0s
  # For SealedSecret CRD
  dependsOn:
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/local/monitoring/kube-prometheus-stack
  prune: true
  validation: client