---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring-flux
  namespace: flux-system
spec:
  interval: 10m0s
  # For PodMonitor CRD
  dependsOn:
    - name: kube-prometheus-stack
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./kubernetes/overlays/local/flux-system/monitoring
  prune: true
  validation: client