apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./gotk-components.yaml
- ./gotk-sync.yaml
# Charts repositories
- charts/banzaicloud-charts.yaml
- charts/flagger-charts.yaml
- charts/grafana-charts.yaml
- charts/jetstack-charts.yaml
- charts/k8s-at-home-charts.yaml
- charts/kubernetes-charts.yaml
- charts/openfaas-charts.yaml
- charts/podinfo-charts.yaml
- charts/prometheus-community-charts.yaml
# Sealed Secrets
- sealed-secrets/sealed-secrets.yaml
# Notifications
- notifications/slack-alert.yaml
- notifications/slack-provider.yaml
- notifications/slack-webhook-url-sealed.yaml
