---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pomerium
  namespace: identity
spec:
  values:
    image:
      repository: "pomerium/pomerium"
      tag: "v0.11.0"

    forwardAuth:
      enabled: true
      internal: false

    config:
      # routes under this wildcard domain are handled by pomerium
      rootDomain: gcp.portefaix.xyz
      generateTLS: false
      insecure: false

      # policy:
      #   - from: prometheus.gcp.portefaix.xyz
      #     to: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      #     # allowed_domains:
      #     #   - outlook.com
      #     allowed_users:
      #       - nicolas.lamirault@gmail.com
    ingress:
      annotations:
        kubernetes.io/ingress.class: "nginx"
        cert-manager.io/issuer: "letsencrypt-prod"
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      hosts:
        - authenticate.gcp.portefaix.xyz
      tls:
        hosts:
          - authenticate.gcp.portefaix.xyz
      secretName: authenticate.gcp.portefaix.xyz-tls


  valuesFrom:
    # - kind: ConfigMap
    #   name: prod-env-values
    - kind: Secret
      name: pomerium-values