apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack-webhook-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgCtv7xdUS899NsL8x7EzepEFFcSMqb5Iy8VbUf05bXoRu3UMftVPSV7O9dc/2t99iMODwllwfMt/xYKi//aBabQOYgPAY1vm0lyMm5fR2txuhLstuS1qcPTJmReGps1HrNLf5en17yeA9937/5v/fQgesi2jo3Zq1oG1L91uURPzYNJTVbUPg220RGVFxifIkIwnFBEIw1XHsAD6e/sxsjt+bxInCZXQe9hLgERD0VFhZPGvWSDeicVHgaGZuqYOK6yeP2FFA0DBP6bch01UM5bNrmJNI2Ic3hXiDI2JDKgFqWf/ECehpEILPtOF0rsi2i+xmnTelb/BNV/mmuAP7GArEAQMe4DkiUSh4Rg1Csr3EbwrlPeHB2pG1w86W0/4gG432POiBY6Kg3KRFEuZz4p4eHQPzKJ5p+HsUnQa5OWy0wQZClPtttJcUQ9YVfr0zyIZFZ3J53w17rlTfzimLMpoXUwcLBwqsmC3Elxc0W2cNyUzQ5rmkEoRHbCji1uSVeVre7pEaNtRmSOxwUVCWMtaV4UiBu5F/yKehH1crvhpvYRyZgLwlxqUlTjrdR38cwbRBtpwzOUqMavRUUEszA852WVDg+ObScmJFvBJnMmKByCOvrn3raqAP9QOI67DS3yQ50scvHOCvhKXQjrF3aTkplOKhA+u3yC1OZSwBxzQBOeHDnd9IsdNLI9N7wr0Qm7MjS9y1GfJjNE42sX56Z1BV9YMPiMv5Ld4xoUOkhO0PGJKybB4seghjgGSQHuLjFCT4qqto1BJoNXvhb3nDirKeQ79QT+THoRENSfZL05
  template:
    metadata:
      creationTimestamp: null
      name: slack-webhook-url
      namespace: flux-system

