---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: flux-system
spec:
  values:
    serviceAccount:
      server:
        annotations:
          iam.gke.io/gcp-service-account: portefaix-prod-velero@portefaix-prod.iam.gserviceaccount.com
    configuration:
      provider: gcp
      backupStorageLocation:
        name: portefaix
        bucket: portefaix-prod-velero
        config:
          serviceAccount: portefaix-prod-velero@portefaix-prod.iam.gserviceaccount.com
      volumeSnapshotLocation:
        name: portefaix
    credentials:
      useSecret: false
    # deployRestic: false
    initContainers:
      - name: velero-plugin-for-gcp
        image: velero/velero-plugin-for-gcp:v1.1.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
