---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: slack-portefaix
  namespace: flux-system
spec:
  type: slack
  channel: general
  secretRef:
    name: slack-url