---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  values:
    loki:
      serviceName: "loki.logging.svc.cluster.local"
    resources:
      limits:
        cpu: 300m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi

    serviceAccount:
      create: true
      name: fluent-bit
      annotations:
        iam.gke.io/gcp-service-account: portefaix-prod-fluentbit@portefaix-prod.iam.gserviceaccount.com
