---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: flux-system
spec:
  values:
    loki:
      config:

        storage_config:
          gcs:
            bucket_name: portefaix-prod-loki

      persistence:
        enabled: false
        accessModes:
        - ReadWriteOnce
        size: 10Gi

      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

      serviceAccount:
        create: true
        name: loki
        annotations:
          iam.gke.io/gcp-service-account: portefaix-prod-loki@portefaix-prod.iam.gserviceaccount.com

    fluent-bit:
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 40m
          memory: 40Mi
