---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  values:
    ingress:
      enabled: false

    config:
      auth_enabled: false
      ingester:
        chunk_idle_period: 3m
        chunk_block_size: 262144
        chunk_retain_period: 1m
        max_transfer_retries: 0
        lifecycler:
          ring:
            kvstore:
              store: inmemory
            replication_factor: 1

          ## Different ring configs can be used. E.g. Consul
          # ring:
          #   store: consul
          #   replication_factor: 1
          #   consul:
          #     host: "consul:8500"
          #     prefix: ""
          #     http_client_timeout: "20s"
          #     consistent_reads: true
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
      schema_config:
        configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
      server:
        http_listen_port: 3100
      storage_config:
        boltdb_shipper:
          active_index_directory: /data/loki/boltdb-shipper-active
          cache_location: /data/loki/boltdb-shipper-cache
          cache_ttl: 24h         # Can be increased for faster performance over longer query periods, uses more disk space
          shared_store: filesystem
        # filesystem:
        #   directory: /data/loki/chunks
        gcs:
          bucket_name: portefaix-prod-loki
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      compactor:
        working_directory: /data/loki/boltdb-shipper-compactor
        shared_store: filesystem

    # extraArgs:
    #   log.level: debug

    persistence:
      enabled: false
      accessModes:
      - ReadWriteOnce
      size: 10Gi

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    serviceAccount:
      create: true
      name: loki
      annotations:
        iam.gke.io/gcp-service-account: portefaix-prod-loki@portefaix-prod.iam.gserviceaccount.com

    serviceMonitor:
      enabled: true





