---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: flux-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: 4.0.0
  interval: 5m
  releaseName: external-dns
  targetNamespace: dns
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        selector:
          release: kube-prometheus-stack
