# Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: alertmanager-config
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgAkTlVbAQQUCWu9c3l0hCT54eBlvOxi2XThrXK+yqoWZPJP/K/ajgZfBOy5bM8wKpbCXihZhzZm9o3aH25G89Rzu5A+4s8kW8+yqO+YJQJjDtsW7q8WZTG9I7upXcPOySRCgoxK20aBjn3B3TNzo3KnF/WV/x7yvrEm3wpUuCZjhD6cjehm82aIEgki/q4A1DWOutdwqhE36yaFm0K6CJMfG6X2/SwYVZuKBnIjh5nIwY7S8cPIPpwZebpYs9XcfsVFIma+OdJlCPOXwhXHWH7DbhwQu9s/PSFrI20AjEZO2jhu/NtmOTfHpmzzHgh2FYI3o1q0iJn9GciSuE8NKrW74aliI/yRpxb1I/MMCV++7qOgapBJlRi4+jSI9LqjSpcc7xKWKUys74Rb/B/YSEf19BS47hfwXKd5QrmYNcDT0rA5WQpcaIhaY0kMgT9RUXjGXE6pz9ODXkwKNofwV4Zz+bSDCF3xDECep+mmqM4fQQVPXE0nlMIXebcpSeR99DMF/4En8CIuLAINsrOw+6QFVZNQ+G1qkA62XlEpkTUzu4odsDQrhrlKKwuPFhQJw3yRiQX7FX+Qxqi8fEKwN5TFRp3ijwz4YKkiOkwGzQCX/GBNMQdSHSfZAHeNWI1XRNpiLWUyar2hAFxp4gQla2fsaPfqoJ22Ayc2DgeekGq2/2OqTeXxdSEWdv9ERdDtk1JfzQ/aI5cjxKS+PT0mafF2LQ08W7HF7glA0YF6e08pMNq1Gpf+Efxo93O9whVzvYTea6nRXpHVInyo1EuVamCbG8NJqAQjhbDhrxU4ftCLIhs9OaDoxbYCfp9Ak4hrZUJxGCgaxJAW0omymDOV4DkLjUYNgWsak9wR5l6q3rjbJZCp/EqBUJDZJgpWeFSjR9hvfBZCET6HKm0jb/MYVtgMO+xc7n532OOu0akc8lq/U00lSSXKTfnWaVXWmfJ5QbrWXGvYXXhrJ7OK1BcHchc/aH3OEJfNYx359Mm/d2UGly2O1lSf5Onew2F2Is1bEzJWM9mzP2BGcKvbJZWkPioVIMf1Owqm+PhhTrKXzSHo2HzywiAIbT3wnHHRjIwmUOy92Bp4macP/7pfpqFk3opgKgKcLzPD29VEcS2KhjtHRS+kSFe9X4F6/GBTKuy8UgZ3ocsJDMaFPksWDv6k3FWiRT+kXcfpaco3pZGcFdHoqvPMLKLMHjxXhO//GJobNmphRoFOZbOCVVa9+T2Snyc93Ud6WjjYXQ5eF8/9llguJsJ60Xk9LEJp/tgT7ua3PFgwmeIV2D9aFs2oMFgUaW1EgrBjrUui6XZV5jqbQmb28DizlkKGtc37VIM/oXURnsD+dst3dSdTIzm6iUPIPrnN+Pz5oUenIGJA4dhKrwfI3SLQvDEZu7fzjnpxtVvMBkt5bXHlgGLHqSviEGKU43NBNPEh7SwqMrsj5bjh+y4QUrlzNhLdIZRvQiJqligfGXLdx9tLJwqYOziIYZFQmFsbUs2U3A+2sfDGgMpjMtH+Vsr2mIjSlC23OobMAWafJ7JLBWi4pQBcyoTUKeOJWV+VZcxZAhP5ySTIke2p0/oAxkQcw3v4GOE5iPBdssOpvOQqTE8N/BalJL16Q0SGZoZ61dYBp13srtzqYHjy7aFc+7uPisxaUdYeQ6B+F0tuTqcP+21MN+Io7N05PvI1lyzCdU3MO9pTmut1X2ax9rGe0cCvNtx7O0coLEBXNrjTFuX6UDagQsxGBUWRmT1GpvcOX258tyDcYLwOnWD4zvb2qVOZN3uiFf74hQKmmmCbNHtSbJUVvMzKdhClCbP9DCaYh0/UV62n7tznDzQJJsJmxWrKcmvPrPWKTuE31iuS7rCUh/NfLKlr0ioUWSWnVOmOqdcKqd0pc3f8q6XjcXHsIInU+twZTP8dB83nbXPZjSPzlhQQUm2FFuXpj8VshEpGbXl2VFmmL+YQIS4KyFuNIgytCbV9vgJJDn18zUmFMTWexcK6+Rwsh4HtgJnhDZbW8hpuuZKY3LEUNcHh1q0JrqtorXqVmUumsk+8b4IAfEAixlAOLgs+zDpXcoz7fnP10khQxtFSzedspF80vB+DRz/0Ac5eCbAgwHAMCewPHMCkK3b5c1a2dyMwe0qsW5xXcudxUkNY3+fBMRb0dvlPgBl6fhsWMbGrSUrWjAIq5FYFUGBGImsp/zRHm1jrm3igNwQuOgruwyVVrBPSHsk15yiM7mpfa9/F63RKBSCBgsMzMoxbj6Ftp5njCBQwCh8Zq116mJ8KSDrawMVVmD9eNu327Q2SdvtWAHVj/hfKYRgw8k1zFFqkRNBDzA5JwivIDxX2hBePepjkAbL5HE/ka8mav/4z8BRubk9wtKA5LFFTbsIAJUzTREzakBliRrHDixx6t2LGHUGUWO5Hh9qyj2UoOr57PuR51WP/B3Jhq+zAE/AOCXoZQY4odlCZfPsarEHWRc/bsulLouAvFnRXb+BSPpY4avGvxamWPvJ+NXyuPhC30I4XTFEbSjAdlS6+R6AZDN4+jgEG0eql5AH15HKFAx96Ol85ZbuXfGbbxguNGi3mNEb9kfwhQ0Degfzk/JQQ9/eDTLziMTvDygiub8dm3khJk6TZMlcwzOGy+HkBtlYp3lbwYrTstQD/+CobV+3f0WMj+ym2YUD4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: alertmanager-config
      namespace: monitoring
