---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: kubernetes-stable-charts
      version: 1.10.0
  interval: 1h0m0s
  releaseName: sealed-secrets
  targetNamespace: kube-system
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 1m
    cleanupOnFail: true
  # values:
  #   ingress:
  #     enabled: false
  #     annotations:
  #       kubernetes.io/ingress.class: nginx
  #       cert-manager.io/cluster-issuer: 'letsencrypt-prod'
  #       nginx.ingress.kubernetes.io/auth-url: 'https://portefaix.xyz/oauth2/auth'
  #       nginx.ingress.kubernetes.io/auth-signin: 'https://portefaix.xyz/oauth2/start?rd=$escaped_request_uri'
  #     hosts:
  #       - sealed-secrets.portefaix.xyz
  #     path: /v1/cert.pem
  #     tls:
  #       - secretName: sealed-secrets.portefaix.xyz-tls
  #         hosts:
  #           - sealed-secrets.portefaix.xyz
