---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  values:
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          # cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          nginx.ingress.kubernetes.io/auth-url: 'https://portefaix.local/oauth2/auth'
          nginx.ingress.kubernetes.io/auth-signin: 'https://portefaix.local/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - chaos-mesh.portefaix.local
        path: /
