---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
  namespace: flux-system
spec:
  values:
    dashboard:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: 'letsencrypt-prod'
          # nginx.ingress.kubernetes.io/auth-url: 'https://gcp.portefaix.xyz/oauth2/auth'
          # nginx.ingress.kubernetes.io/auth-signin: 'https://gcp.portefaix.xyz/oauth2/start?rd=$escaped_request_uri'
        hosts:
          - name: chaos-mesh.gcp.portefaix.xyz
            paths: ["/"]
            tlsSecret: chaos-mesh.gcp.portefaix.xyz-tls

